version: '3'
services:
  ghost:
    image: ghost:latest
    restart: always
    depends_on:
      - db
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: CHANGE_ME
      database__connection__database: ghost
    ports:
      - "2368:2368"
    volumes:
      - ./ghost_content:/var/lib/ghost/content
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CHANGE_ME
    volumes:
      - ./ghost_mysql:/var/lib/mysql
